### ISSUE TITLE
Ability to set session properties

### ISSUE THREAD

**Issue by Btwitzke** [findinpath/dbt-trino#4]
Looks like using the trino (or presto) python client allows for setting session properties, however there is currently no way to set these and have them persist into the transaction when running dbt. Also it appears the python client needs this set in the actual connection. If a pre-hook is run, that also is run outside of a transaction of course and does not effect the running queries. Having the option to set session parameters can significantly increase the performance for pipelines through Trino. 

Init from connect does include session_properties in trino-python-client.
```
def __init__(
        self,
        host,
        port=constants.DEFAULT_PORT,
        user=None,
        source=constants.DEFAULT_SOURCE,
        catalog=constants.DEFAULT_CATALOG,
        schema=constants.DEFAULT_SCHEMA,
        session_properties=None,
        http_headers=None,
        http_scheme=constants.HTTP,
        auth=constants.DEFAULT_AUTH,
        redirect_handler=None,
        max_attempts=constants.DEFAULT_MAX_ATTEMPTS,
        request_timeout=constants.DEFAULT_REQUEST_TIMEOUT,
        isolation_level=IsolationLevel.AUTOCOMMIT,
        verify=True
    ):
```

**Comment by findinpath** [comment]
Thank you @Btwitzke  for raising this issue.

Do you have any suggestion on where to specify the session properties for Trino within `dbt` ?

**Comment by Btwitzke** [comment]
Thanks for the quick response @findinpath !

I think that there are 2 ways of looking at this:

1) As you mentioned, since this is going into the actual connection then it could be specified in the trino dbt profile along with the rest of the connection details. This would be a good place to start for this.

2) To expand functionality in another step, it is sometimes desired to specify different session variables for different models, rather than a wholesale connection variable in the profile. An example is raising the amount of task writers when knowing that a model produces larger data files and not wanting so many writers when a model has a small amount of data. In that sense, the optimal way would be the ability to specify session variables in the same type of 'pre-hook' syntax within a model or in the dbt_project.yml.

**Comment by findinpath** [comment]
@Btwitzke the 2nd point you've raised points rather to a one off "hint" for Trino that you want to use for a specific query.

Do you have a recipe for such a scenario when interacting directly with Trino?

**Comment by Btwitzke** [comment]
@findinpath Yes, a hint it a way to put it. Setting the session variables within a pre-hook currently does not actually effect the running queries. It appears that upon a new transaction, a new connection is made which resets the session properties of course. I tested running 'set session' queries in a pre-hook, and these do NOT persist into the corresponding model query. I think that is because a pre-hook is actually run as a separate query before the model.

If there was the ability to set session properties in the profiles.yml that would also work for this case, and most likely the simplest solution since those variables essentially already persist into the connections made.

**Comment by findinpath** [comment]
@Btwitzke I had a look on the dbt logs when testing the changes from @hovaesco  and it seems that after each query, a new Trino connection is being opened:

```
Opening a new connection, currently in state closed
```

This generate the loss of the settings set on pre-hook.

For now, we can use the  session properties set in the `profiles.yml` dbt file.

Please do create a new issue if you have an idea on how to make use of session properties that are to be applied only on a specific query.
