### ISSUE TITLE
bump version

### ISSUE THREAD

**Issue by Btwitzke** [findinpath/dbt-trino#8]
Is it possible to update the version for download through PyPi ? I am using some docker images for dbt and would like to be able to pull the updated version of this package during build to get some recent updates. Currently it pulls 0.20.0.

**Comment by findinpath** [comment]
Thank you for your request.

You can find now the latest version of dbt-trino at:

https://pypi.org/project/dbt-trino/0.20.2/


Please do share some experience about your usage of dbt-trino 

Do you plan anywhere soon to use it in a productive scenario?

**Comment by Btwitzke** [comment]
Thank you @findinpath ! We are planning to use dbt-trino in production shortly. Thanks to the contributions on dbt-trino, this makes our pipelines much more efficient during testing! Very happy to see you were able to take dbt-presto and continue moving it forward with current changes.

I plan to become more active with this package as we begin to write further pipelines utilizing dbt and trino.

**Comment by findinpath** [comment]
@Btwitzke could you briefly share a bit what kind of productive scenarios do you have in mind?

This would help us to focus on specific further developments.

**Comment by Btwitzke** [comment]
@findinpath Yes, we have some longer running pipelines on relatively large data sets, and that has helped to drive the need to have some customizable parameters to speed up the process. The data is appended to frequently, and thus will change the end models. Performance of dbt with trino has become a focal point to get into a production scenario.
